CREATE TABLE PERSON (
    ID bigint NOT NULL AUTO_INCREMENT,
    SSN varchar(255) NOT NULL UNIQUE ,
    FIRST_NAME varchar(255) NOT NULL,
    LAST_NAME varchar(255) NOT NULL,
    GENDER varchar(255) NULL,
    PRIMARY KEY (ID)
);
